#ifndef SPIFLASH_LAYOUT_H
#define SPIFLASH_LAYOUT_H

#include <stdint.h>

/* Update capacity and partitions here when replacing the SPI Flash device. */
#define SPIFLASH_TOTAL_SIZE            0x00800000UL
#define SPIFLASH_SECTOR_SIZE           0x00001000UL

#define SPIFLASH_OTA_PARTITION_NAME    "ota_backup"
#define SPIFLASH_OTA_OFFSET            0x00000000UL
#define SPIFLASH_OTA_SIZE              0x00080000UL

#define SPIFLASH_CONFIG_MAIN_PARTITION_NAME   "config_main"
#define SPIFLASH_CONFIG_MAIN_OFFSET    0x00080000UL
#define SPIFLASH_CONFIG_MAIN_SIZE      0x00010000UL
#define SPIFLASH_CONFIG_BACKUP_PARTITION_NAME "config_backup"
#define SPIFLASH_CONFIG_BACKUP_OFFSET  0x00090000UL
#define SPIFLASH_CONFIG_BACKUP_SIZE    0x00010000UL

#define SPIFLASH_RESERVED_OFFSET       0x000A0000UL
#define SPIFLASH_RESERVED_SIZE         0x00060000UL

#define SPIFLASH_LOG_PARTITION_NAME    "log_tsdb"
#define SPIFLASH_LOG_OFFSET            0x00100000UL
#define SPIFLASH_LOG_SIZE              0x00100000UL

#define SPIFLASH_IMAGE_PARTITION_NAME  "image"
#define SPIFLASH_IMAGE_OFFSET          0x00200000UL
#define SPIFLASH_IMAGE_SIZE            (SPIFLASH_TOTAL_SIZE - SPIFLASH_IMAGE_OFFSET)

#if ((SPIFLASH_CONFIG_MAIN_OFFSET % SPIFLASH_SECTOR_SIZE) != 0U) || \
    ((SPIFLASH_CONFIG_BACKUP_OFFSET % SPIFLASH_SECTOR_SIZE) != 0U) || \
    ((SPIFLASH_LOG_OFFSET % SPIFLASH_SECTOR_SIZE) != 0U) || \
    ((SPIFLASH_IMAGE_OFFSET % SPIFLASH_SECTOR_SIZE) != 0U)
#error "SPI Flash partition offsets must be sector-aligned"
#endif

#if ((SPIFLASH_CONFIG_MAIN_OFFSET + SPIFLASH_CONFIG_MAIN_SIZE) != SPIFLASH_CONFIG_BACKUP_OFFSET) || \
    ((SPIFLASH_CONFIG_BACKUP_OFFSET + SPIFLASH_CONFIG_BACKUP_SIZE) != SPIFLASH_RESERVED_OFFSET) || \
    ((SPIFLASH_RESERVED_OFFSET + SPIFLASH_RESERVED_SIZE) != SPIFLASH_LOG_OFFSET) || \
    ((SPIFLASH_LOG_OFFSET + SPIFLASH_LOG_SIZE) != SPIFLASH_IMAGE_OFFSET)
#error "SPI Flash partition layout contains an unexpected gap or overlap"
#endif

#if ((SPIFLASH_IMAGE_OFFSET + SPIFLASH_IMAGE_SIZE) != SPIFLASH_TOTAL_SIZE)
#error "SPI Flash partition layout must consume exactly the device capacity"
#endif

#endif /* SPIFLASH_LAYOUT_H */
